-- +migrate Down
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS reactions;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS PostTopics;
DROP TABLE IF EXISTS messages;

